# LOGGIN PATTERN
loggin.pattern.console="%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:~%5P} %M%N"
# VARIABLES DE ENTORNO PARA SEGURIDAD
config.security.oauth.client.id=frontendapp
config.security.oauth.client.secret=12345
#config.security.oauth.jwt.key=