# Puerto por donde Eureka Server va a estar escuchando las peticiones y registro de nuestros microservicios.
spring.application.name=gateway-service
server.port=9093
#
#
# Gateway Config
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.routes[0].id=msvc-clientes
spring.cloud.gateway.routes[0].uri=lb://msvc-clientes
spring.cloud.gateway.routes[0].predicates=Path=/stephkids/api/cliente/**
spring.cloud.gateway.routes[1].id=msvc-inventarios
spring.cloud.gateway.routes[1].uri=lb://msvc-inventarios
spring.cloud.gateway.routes[1].predicates[0]=Path=/stephkids/api/producto/**, /stephkids/api/wishlist/**
spring.cloud.gateway.routes[2].id=msvc-ventas
spring.cloud.gateway.routes[2].uri=lb://msvc-ventas
spring.cloud.gateway.routes[2].predicates=Path=/stephkids/api/factura/**
spring.cloud.gateway.routes[3].id=msvc-comentarios
spring.cloud.gateway.routes[3].uri=lb://msvc-comentarios
spring.cloud.gateway.routes[3].predicates=Path=/stephkids/api/comentarios/**
#      - Path=/api/v1/first/**
#
#
# Eureka Config
eureka.client.serviceUrl.defaultZone=http://localhost:9092/eureka/
#
#
# Desabilitar Ribbon para que Spring Cloud use Load balancer que es propio de del mismo.
spring.cloud.loadbalancer.ribbon.enabled=false
#
#
# Configuracion, para el servidor de configuracion. Necesario para las ultimas versiones de spring cloud y que pueda funcionar como cliente de servidor de configuraciones
# https://www.udemy.com/course/microservicios-con-spring-boot-y-spring-cloud/learn/lecture/27990942#overview
#
#
#app.jwt.secret=RSK0707!RSK0707!RSK0707!RSK0707!RSK0707!RSK0707!RSK0707!RSK0707!RSK0707!RSK0707!
#app.jwt.expiration-in-ms=86400000