# Puerto por donde Eureka Server va a estar escuchando las peticiones y registro de nuestros microservicios.
server.port=9000
spring.application.name=msvc-upload-files
server.servlet.context-path=/stephkids
#
#
# Datasource
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=steph_kids_web;TrustServerCertificate=True;
spring.datasource.username=sa
spring.datasource.password=mrconejO.07
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.main.allow-bean-definition-overriding=true
#
#
# JPA/Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=create-drop
#(create, create-drop, validate, update)
#
#
# Eureka Config
eureka.client.serviceUrl.defaultZone=http://localhost:9092/eureka/
#
#
# Firebase
firebase.bucket-name=steph-kids-web.appspot.com
firebase.image-url=https://storage.googleapis.com/${firebase.bucket-name}/%s