#Configuracion propia de Docker (host.docker.internal) para que pueda comunicarse con la base de datos!
spring.datasource.url=jdbc:sqlserver://host.docker.internal;databaseName=steph_kids_web;TrustServerCertificate=True;
spring.datasource.username=sa
spring.datasource.password=mrconejO.07
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.main.allow-bean-definition-overriding=true 
#
#
#
spring.cloud.loadbalancer.ribbon.enabled=false